homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum

config.schema.json
Added config.scheme.json. Now the plugin support native changing setting via web interface (homebridge-config-ui-x)
=> Add support homebridge-config-ui-x

index.js
As discussed in #46, added a more generic logic that will rely on the model's speed modes definition.
Also removed the `[object Object]` socket log message.
Please, feel free to change anything you want to :)
=>  Add 3rd Gen support

README.md
Anleitung? Cute, but distracting. Fixed to English "Instructions".
=> Update Instructions Title 'Anleitung'.

index.js
=> Refresh the state every 30s to ensure miio is still properly connected

index.js
Reverts nicoh88/homebridge-xiaomi-roborock-vacuum#82
=> Revert "Refresh the state every 30s to ensure miio is still properly connected"

README.md, config.schema.json, index.js, models/index.js, models/models.js, models/speedmodes.js, models/watermodes.js
Fixes #79 
Trying to support the water box mode in S5 Max.
@infernalK I'd appreciate it if you can test these changes on your end by installing it from this branch in git.
=> Try to support the new WaterBox property

config.schema.json, index.js, package.json
Hey,
i implement the start Delay for testing
Reference : https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum/issues/120
I think we should make it optional ?
@afharo and @nicoh88
=> Startdelay for testing

models/models.js
=> Add model roborock.vacuum.m1s

README.md, config.schema.json, index.js
Hey,
this can be added to the dev channel.
User @domeOo and i figured out when get_room_map is working and when not. I make an readme Point for that!
Also implement Zone cleaning
@afharo & @nicoh88
=> AutoRoom Generation (for the dev branche)

models/models.js, package.json
=> Add Roborock T4 to gen3 list

index.js
=> [Fix] roboError can be null

README.md, index.js
Provides the ability to create individual zones that can be individually run from Home.
=> Adding ability to create zones

index.js
Clear the `error_code` state after logging.
Closes #93
=> Remove duplicated errors

models/models.js
Add Roborock s6 pure to list of models.
This closes #175
=> Add Roborock S6 Pure to list of models

index.js, package.json
Testing if reducing the number of requests (especially when only reading properties) helps with making the responses to work faster
=> Reduce number of calls

models/models.js, models/speedmodes.js
Fixes https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/175 for my Xiaowa E202-02 vacuum with 1.3.0_0752 firmware
Not sure if there are any other models which are reported as e2 - if yes, this PR will probably break them
=> Xiaowa e202 02 speed mode

index.js
Fixes https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/187
=> Fix issues 187 min step rotation

.github/workflows/nodejs.yml, .gitignore, index.js, models/speedmodes.js, package-lock.json, package.json
=> Add Github actions

CHANGELOG.md, index.js, miio/lib/checkResult.js, miio/lib/devices/mijiavacuum.js, miio/lib/devices/vacuum.js, miio/lib/devices/viomivacuum.js, miio/lib/models.js, models/models.js, models/speedmodes.js, package-lock.json, package.json
- [Models] S5 should use the gen4 speeds (#131)
- [Models] Add support for Viomi models (#100 #199 #150)
- [Models] Some Mijia models use a mix of a set of commands of Viomi and Roborock :scream: (#141)
- [Bug] Set `error_code` to `0` after logging it to clear it up (#193)
=> Next (possibly 0.11.0)

CHANGELOG.md, index.js, package-lock.json, package.json
- [Bug] Avoid services requests while the device is not connected yet (#251)
=> 0.12.1 release

index.js
=> [Bug] Callbackify is missing

models/models.js
Adds the config for the model roborock.vacuum.a11
=> Add Roborock T7 (roborock.vacuum.a11)

index.js
Uses the speed modes selected for the Waterbox to report the ON/OFF status. Similarly, it uses the OFF requests to set the speed to 0%.
Resolves #284.
=> [Waterbox] Add ON/OFF characteristics controls

models/models.js
=> Fix speed mappings for rockrobo.vacuum.v1

README.md, index.js, miio/lib/devices/vacuum.js, miio/lib/devices/viomivacuum.js
- Once user toggle one Room switch, robot will start the room based cleaning just for that room
- While user toggling the Room switches, cleaner will not take any action. 
- After selecting the rooms want to be cleaned by toggling the Room switches, user can start the room based clean by turn on the fan.
Thanks to the original PR
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/200
=> Added: support delay start for room cleaning

CHANGELOG.md, index.js
=> [Bug] Fix autoroom bug after Services renamed

.github/workflows/nodejs.yml, .gitignore, __snapshots__/index.test.js.snap, index.js, index.test.js, mocks.js, package-lock.json, package.json
Still a work in progress.
I'm aiming for good coverage of the unit-tests so the next steps (migrating to Platform, refactorings, etc.) are performed with the confidence that we are not breaking the way it works
Closes #171
=> Unit Tests

CHANGELOG.md, models/models.js, models/models.test.js, models/speedmodes.js
Resolves #311 
Reverting changes in #296
=> Fix rockrobo.vacuum.v1 speeds

README.md
Added a link to the Xiaomi Cloud tokens extractor python script that makes token extraction incredibly easy.
=> Add token extractor link to readme

CHANGELOG.md, index.js, package-lock.json
=> Pause option should always return something

CHANGELOG.md, index.js, package-lock.json, package.json
To fix the issue it tried to solve in first place, we should double down on registering the plugin as a platform (#247).
=> Delete `delay` option

lib/callbackify.test.js, lib/safeCall.test.js
=> Better test coverage

CHANGELOG.md, config.schema.json, miio/lib/network.js
=> Remove # from private methods

models/models.js
Resolves https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/495
=> Added support for S7 MaxV

README.md, config.schema.json, index.js, miio/lib/devices/vacuum.js
- configuration for optional button with: name, x-coordinate, y-coordinate
- logic to send robot vacuum to location
- explanation to make finding the right coordinates somewhat easier
- You need to start/stop the vacuum to send it back to its dock. My way is actually pressing the dock button on the vacuum, as I send it to the bin anyway...
- The default name of the button is highly opinionated - after all that's why I built this 😅 
Please let me know if I can improve it somehow.
=> Go To Button

src/xiaomi_roborock_vacuum_accessory.js
=> [Hotfix] Fix callbackify imports

.npmignore, .prettierignore, CHANGELOG.md, babel.config.js, jest.config.js, package.json, src/miio/cli/device-finder.js, src/miio/lib/devices/vacuum.js, src/miio/lib/devices/viomivacuum.js, src/models/speedmodes.ts, src/services/__snapshots__/care_service.test.ts.snap, src/services/care_service.test.ts, src/services/care_service.ts
=> Handle negative responses to the filters

CHANGELOG.md, package-lock.json, package.json
=> Add dependency to `hap-nodejs`

src/services/battery_info.ts, src/services/care_service.test.ts, src/services/care_service.ts, src/services/dock_service.ts, src/services/dust_bin_service.ts, src/services/dust_collection.ts, src/services/find_me_service.ts, src/services/go_to_service.ts, src/services/main_service.ts, src/services/pause_switch.ts, src/services/product_info.ts, src/services/rooms_service.ts, src/services/water_box_service.ts, src/services/zones_service.ts, src/test.mocks.ts, src/xiaomi_roborock_vacuum_accessory.ts
Resolves #529
I need to validate this with `homebridge` folks
=> Setters should return null

config.schema.json
=> make dustBin beta visible in configuration

src/services/device_manager.test.mock.ts, src/services/device_manager.test.ts, src/services/find_me_service.test.ts, src/test.mocks.ts, src/xiaomi_roborock_vacuum_accessory.test.mock.ts, src/xiaomi_roborock_vacuum_accessory.test.ts, src/xiaomi_roborock_vacuum_accessory.ts
=> Add more tests

src/xiaomi_roborock_vacuum_accessory.test.ts, src/xiaomi_roborock_vacuum_accessory.ts
Part of #171
Last one for today 😇
=> More coverage

CHANGELOG.md, src/miio/lib/devices/viomivacuum.js, src/services/device_manager.ts, src/services/product_info.test.ts, src/services/product_info.ts, src/utils/constants.ts
Using the [Viomi implementation](https://github.com/rytilahti/python-miio/blob/dc55eba816e1c60480480a39fc2bbaa2dc3b5c66/miio/integrations/vacuum/viomi/viomivacuum.py) from the `python-miio` library, I tried to add some improvements to the Viomi models.
It might fix the following #216, #221, #283, #443, #450, #328, #474, #345
=> Viomi: Fix missing bits

src/miio/cli/commands/protocol/call.js
While debugging, I noticed this CLI helper was not working...
=> [miio] Fix CLI protocol call request

CHANGELOG.md, src/services/care_service.test.ts, src/services/main_service.mock.ts, src/services/product_info.mock.ts, src/services/water_box_service.test.mock.ts, src/services/water_box_service.test.ts, src/services/water_box_service.ts, src/utils/logger.mock.ts
Resolves https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/764#issuecomment-1712083333
=> Fix waterbox off behaviour (#764)

CHANGELOG.md, src/models/models.ts
Related to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/788#issuecomment-1712322686
Adding speeds for the Q-Revo
=> [Q-Revo] Initial support

package.json, src/services/main_service.ts, src/services/rooms_service.ts, src/test.mocks.ts
=> Fixed: push room names from settings to homekit

CHANGELOG.md, package-lock.json, package.json, src/services/battery_info.ts, src/services/custom_care_service/characteristics/care_filter.ts, src/services/custom_care_service/characteristics/care_main_brush.ts, src/services/custom_care_service/characteristics/care_sensors.ts, src/services/custom_care_service/characteristics/care_side_brush.ts, src/test.mocks.ts
Resolves #958
@mitch7391, would you mind helping me figure out if these changes are enough?
Is it safe to merge for the current version of Homebridge? (my tests tend to indicate it is, and I checked HAP-Nodejs' code and it looks like 0.12 supports both, but I'd like to confirm).
=> Prepare for Homebridge v2

CHANGELOG.md, package-lock.json, package.json
Resolves https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/958
=> Homebridge v2: Explicitly declared compatibility

CHANGELOG.md, src/models/models.ts
Resolves https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/868
=> Add waterbox support for Roborock S7 Max Ultra

README.md
Small PR - Commit 757cef36262199676834126ccf29a4e9cb81bdab moved the guide file. This PR adjusts sources to changes. It also fixes a few typos along the way in those files.
_Also Please fix the `Vaccum` -> `Vacuum` in the About section of the repository._
=> Update protocol guide reference

README.md
Solves #420 with new more detailed description of zone cleaning
=> Zone cleaning documentation
