index.js, lib/callbackify.js
As agreed on #44 I've moved all the state variables to actually query the robot for the status on every time Homebridge asks for it. I've used promises (async/await) because I felt it was easier to handle all the asynchronous calls without having a super-nested code (that you get with callbacks).
I've been testing it all this time at home (with all the features, including Pause and the Dock Sensor) and everything seems to work.
On top of that, I've added a new re-connection mechanism (still testing it though).
Sorry if it feels too much of a change. I'm happy to publish it as a side library if you don't want to update yours with this. :)
=> Refactoring

index.js
> If you start / restart the Homebridge and the Xiaomi is off / battery is empty - then the plugin can not reach the robot.
> It comes: "ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout“ show here line 402.
> Because the Homebridge does not get a Return / Error from homebridge-xiaomi-roborock-vacuum, the Homebridge hangs when the plugin is loaded and no devices in the Homebridge are accessible. In the Apple Home app, all devices from this Homebridge display "No Answer" or "Refresh“.
Instead of hanging forever until the device is connected, I've moved the retries to a setTimeout. That way the promise will either resolve or reject straight away. But we'll keep a retry to connect on every 2 minutes.
Still, whenever there's a new GET/SET …
=>  Controlled Connection Retries

index.js
fanSpeed map is correct, but missing vacuum mode for roborock.vacuum.t6,
so it can't find this mode and use default XiaomiRoborockVacuum.speedmodes_gen1 fanSpeed map to continue.
=> fix roborock.vacuum.t6 fanSpeed not supported issue

index.js
I reread the issue and better understood the logs you shared (thank you for that).
The error is that the method `this.connect()` in the `constructor` is rejecting a promise and there is no catch around it. Not anything awaiting the promise. This usually leads to the entire NodeJS process to crash. 
It's a simple solution. Simply adding an empty `catch` in the constructor because the method itself already tries to reconnect after 2 minutes.
Fixes #81
=> Fix UnhandledPromiseRejectionWarning on startup when it fails to connect

index.js, lib/safeCall.js
Fixes #91 
Those errors seem to be controlled errors. More like warnings. Maybe it's better to simply log them (as we do now in the method `this.changedError` and to stop throwing it.
I'd love it if we can find a way (via Homebridge) to show the error notification in the Home app. That's something to investigate.
=> Do not throw on state.error

index.js
Fixes #94 
In the `changed*` methods, we'll only log the changes when a new value is in. This way the new state polling every 30s doesn't generate too many log entries.
NB: I intentionally left the `debug` messages out of the check.
=> Reduce changed logs by only logging when the value is actually new

index.js
Fixes #99 
Added empty catches in those promises that are not handled by a catch in the wrapper function (either because in a `setInterval` or in the `constructor`)
=> Revisit the unhandled promises

index.js, package.json
Fixes #89 
We now can add a list of valid speed-sets, the one in the bottom supersedes the ones on top, only if the `firmware` version expression (from `semver`) is valid (if specified).
=> Find speed taken into account the firmware if specified

index.js
Fixes #105 
When the speed is set to 0, it will call the go to the dock method instead of changing the speed to 0 (as changing the speed is actually setting a mode and some models apparently understand that mode as something else 😓).
@Tim2309 could you try the logic on this branch?
You can install from `git` instead of `npm`, by running these methods:
```
sudo su -
npm install -g afharo/homebridge-xiaomi-roborock-vacuum#stop-on-speed-0
```
=> Stop on speed 0

index.js
Fixes #114 
When having multiple Services of the same type, we need to provide a subtype or home bridge will fail. Now, with the addition of the rooms' switches, we need to provide a subtype name to the Pause switch
=> Add subtype to the Pause Switch

README.md, index.js
This pull request adds an automatic retrieval of roomIDs via an inactive timer for room cleaning set up. It was suggested in issue #149. Instructions on how to set the config file and how to set the timer are in the README.md
The PR introduces a new member variable saving the room mapping. This is since the HomeKit services need to be created before the robot can be queried for room ids. This way it is possible to change the after service creation as soon as it is known.
=> Autoroom on roborock s5

index.js, package.json
Fix #151 
@c-o-m-m-a-n-d-e-r it looks like that compilation error in #151 is due to the installation of `system-sleep` in that environment. 
Does it make sense if we move it to optional dependencies?
=> Move system-sleep to optional dependencies

CHANGELOG.md, README.md, config.schema.json, index.js, lib/callbackify.js, lib/safeCall.js, models/index.js, models/models.js, models/speedmodes.js, models/watermodes.js, package.json
As the number of maintainers is growing 🎊 and in order to maintain some sense of the code. I think it makes sense to have a linter/formatter that will unify the code style in this project. I'm installing `prettier` as some sort of `standard` to help us with maintaining the style. 
We'll investigate in the future ways to block PRs unless prettier is successful (it should be easy with Github workflows/Travis CI or any other automated workflows).
=> Use Prettier for code styling enforcement

index.js, models/speedmodes.js
Fixes #131 
This PR implements @maisun's suggestion to evenly spaced the modes in the `RotationSpeed` so we can set the Homekit's property `minStep`.
This should make it easier to control via the app, since it won't jump 1-by-1% but it will directly jump to the allowed speeds.
⚠️ It may be considered a breaking change since it may affect some automation for folks out there. Remember to mention it in the changelog if this PR is accepted.
=> Proportional steps in speed + RotationSpeed.minStep

index.js
Fixes #145 
Use the native `FilterMaintenance` service for the Care indicators (sensors, filter, side brush and main brush).
I'm not removing the custom ones should someone is using them already.
=> Use native FilterMaintenance service for the Care indicators

index.js
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/146
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/180
=> Fixes issues/146 and issues/180

CHANGELOG.md, index.js, package.json
To test it, make sure you install `homebridge-xiaomi-roborock-vacuum@next` and restart your homebridge server.
- [Bug] Xiaowa E202-02 fails to go back to the dock (#181) - Thanks @bedrin
- [Bug] Xiaowa E202-02 successful response is upper-cased "OK" - Thanks @bedrin
- [Bug] Pause before going to dock (#180) - Thanks @bedrin
- [Bug] Fixes connection drops and outdated statuses (#146) - Thanks @bedrin
=> Next (0.9.0)

package-lock.json, package.json
I didn't update `tinkerhub-discovery` because it has some breaking changes we'll need to tackle in a different issue. 
But no vulnerabilities anyway :)
```zsh
➜  homebridge-xiaomi-roborock-vacuum git:(update-deps) ✗ npm i
npm WARN homebridge-xiaomi-roborock-vacuum@0.10.0 requires a peer of homebridge@>=0.4.45 but none is installed. You must install peer dependencies yourself.
added 1 package from 3 contributors, removed 4 packages, updated 1 package and audited 126 packages in 0.904s
32 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
=> Update dependencies to remove the vulnerability warnings

index.js
We are getting many issues claiming errors when it looks more like connection issues or wrong tokens (i.e. #248)
This PR avoids making Services `get`/`set` calls until `this.device` exists.
=> Avoid services requests while the device is not connected yet

miio/cli/commands/discover.js, miio/cli/commands/inspect.js, miio/cli/commands/protocol/call.js, miio/cli/device-finder.js, miio/lib/discovery.js
This allows running: 
```sh
miio-vacuum discover --token 636e4xxxxxxxxxx
miio-vacuum inspect 192.168.xxx.xxx --token 636e4xxxxxxxxxx
miio-vacuum protocol call 192.168.xxx.xxx miIO.info --token 636e4xxxxxxxxxx
```
And get an enriched response to test out things and make troubleshooting easier.
=> CLI: read token from the options

index.js
Throw an error explaining `autoroom` and `rooms` can't be used at the same time.
We've got tons of issues asking for the room feature not working and it usually turns out they forget to remove `"autoroom"`.
=> Validate if autoroom and rooms are used at the same time

README.md
As [noted](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/242#issuecomment-653926477) by @enz1ey, the fully-automatic room discovery works on additional models with newer firmware versions.
This updates the readme to reduce confusion around using the semi-automatic discovery method with vacuums on newer firmware, which may no longer work properly.
I confirmed with my Roborock S4 on firmware 3.5.8_0358 that the semiautomatic discovery was not working:
```ERR getRoomList | roborock.vacuum.s4 | Could not find a timer for autoroom```
but that rooms were discovered successfully after naming them in the Mi Home app and setting `autoroom: true`.
Fixes #242
=> Note that autoroom works on more Roborock models

models/models.js
the correct model is roborock.vacuum.a09 instead of roborock.vacuum.a9
=> Update model.js to support T7 Pro

CHANGELOG.md, index.js
Resolves https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/324#issuecomment-735756653
In the `autoroom` feature, when used as an array, the `roomId` is initially a dummy counter and it's populated later on as the plugin discovers the rooms. For that reason, the callbacks need to refer to the property `.roomId` attached to the service instead of the original `roomId` sent over
=> [autoroom] Use service's attached .roomId

CHANGELOG.md, index.js
Fixes #373
For some models, we get `undefined` when obtaining the serial number. Let's ensure it's a string.
=> Ensure SerialNumber is a string

CHANGELOG.md, index.js
Resolves #366
Fixes an issue when percentages could be over 100% when maintenance is long overdue, so `FilterLifeLevel` could potentially be < 0.
=> Fix care percentages

.npmignore
Resolves #376
Dry-Run publish returns
```
npm notice === Tarball Details === 
npm notice name:          homebridge-xiaomi-roborock-vacuum       
npm notice version:       0.17.1                                  
npm notice package size:  43.6 kB                                 
npm notice unpacked size: 179.9 kB                                
npm notice shasum:        cc682e8e73e63da004840d65edbad73da6414a50
npm notice integrity:     sha512-ywIlzhqmUeVJt[...]lZFwUi8dnyO2Q==
npm notice total files:   44                                      
npm notice 
```
That's a reduction of almost 400kB
=> Reduce NPM bundle size

README.md
Added a link to a new German step-by-step guide on how to get the token via tokenextractor, configure the plugin and mapping the rooms.
=> Add new German tutorial link to README.md

CHANGELOG.md, miio/lib/devices/viomivacuum.js
Viomi models fail to return the serial number. Since it's not a critical piece of information. We'd rather stop requesting it over showing errors in the logs that confuse the users and create a lot of noise.
```
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
at module.exports.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
at XiaomiRoborockVacuum.getSerialNumber …
```
=> [Viomi] Skip SerialNumber retrieval

src/__snapshots__/xiaomi_roborock_vacuum_accessory.test.ts.snap, src/services/battery_info.ts, src/services/care_service.test.ts, src/services/care_service.ts, src/services/dock_service.ts, src/services/dust_collection.ts, src/services/find_me_service.ts, src/services/go_to_service.ts, src/services/index.ts, src/services/main_service.ts, src/services/pause_switch.ts, src/services/plugin_service_class.ts, src/services/product_info.ts, src/services/rooms_service.ts, src/services/types.ts, src/services/water_box_service.ts, src/services/zones_service.ts, src/xiaomi_roborock_vacuum_accessory.ts
Part of #458.
In order to change the `Fan` to be a `Switch`, we need to rename the service to `main` so the name is unlinked to the actual HB service type
=> Rename `fan` to `mainService`

src/index.ts, src/xiaomi_roborock_vacuum_accessory.test.ts, src/xiaomi_roborock_vacuum_accessory.ts
Looking at the example https://github.com/homebridge/homebridge-examples/blob/master/accessory-example-typescript/src/accessory.ts, I noticed the HB API is sent as a parameter to the constructor of the class, so we don't need to copy them as global variables anymore.
=> Simplify accessory export

.github/workflows/nodejs.yml
Ideally, each step should be shown separately in the checks to make it more obvious which one failed.
=> CI: Split build steps

.github/workflows/nodejs.yml
Showing the path of the `.github/workflows/nodejs.yml` instead of "CI" in the list of checks is ugly 😇
=> Add CI name

CHANGELOG.md, src/xiaomi_roborock_vacuum_accessory.ts
Tries to resolve #542 by applying these changes:
* It returns the main fan/switch service first in the list of services.
* On top of that, it explicitly sets all other services as non-primary and linked to the main fan/switch service.
cc @luc-ass do you think this might work?
=> Enforce (or try to) the right order of the services

CHANGELOG.md, src/services/dock_service.ts, src/services/main_service.ts, src/services/rooms_service.ts, src/services/zones_service.ts
Resolves #546.
Resolves #559
* All the services subscribe to the stateChanged$ observable and apply the changes.
* The `distinct` clause is only used for logging purposes, but services always update the service (just in case).
=> Reset switches after cleaning is complete

CHANGELOG.md, src/services/device_manager.ts, src/services/rooms_service.test.ts, src/services/rooms_service.ts
Resolves #609
If the connection was not established before the autoroom discovery logic took place, the plugin crashes.
This PR holds that logic from running until the connection is successfully made.
=> [Room Service] Wait for connection before applying the auto-room discovery

.github/workflows/nodejs.yml
Changing the CI to always run the tests against the current version of Node.js, the active LTS, and the previous LTS.
=> [ci] Node.js matrix based on LTS versions

.gitignore, .npmignore, .vscode/settings.json, CHANGELOG.md, src/services/dock_service.ts, src/services/dust_collection.ts, src/services/find_me_service.ts, src/services/go_to_service.ts, src/services/pause_switch.ts, src/services/rooms_service.ts, src/services/water_box_service.test.ts, src/services/water_box_service.ts, src/services/zones_service.ts, src/test.mocks.ts, src/utils/ensure_name.test.ts, src/utils/ensure_name.ts
Follow up to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/829, but extending that logic to all the services/accessories.
Additionally, it resolves https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/841: when the user applies a name override, it'll persist it, so that it knows it shouldn't reapply the names.
=> Fix iOS16 naming issues but preserving user overrides
